const TERMOS_SUPLEMENTO = [
  'whey',
  'protein',
  'proteina',
  'proteína',
  'creatina',
  'creatine',
  'bcaa',
  'glutamina',
  'glutamine',
  'beta alanina',
  'beta-alanina',
  'pre treino',
  'pre-treino',
  'pre workout',
  'pre-workout',
  'termogenico',
  'termogênico',
  'cafeina',
  'cafeína',
  'caffeine',
  'vitamina',
  'vitamin',
  'omega 3',
  'omega-3',
  'omega3',
  'colageno',
  'colágeno',
  'collagen',
  'magnesio',
  'magnésio',
  'magnesium',
  'zinco',
  'zinc',
  'probiotico',
  'probiótico',
  'probiotic',
  'suplemento',
  'suplement',
  'coenzima',
  'coenzyme',
  'q10',
  'resveratrol',
  'curcumina',
  'curcumin',
  'cúrcuma',
  'cla',
  'l-carnitina',
  'carnitina',
  'carnitine',
  'maltodextrina',
  'maltodextrin',
  'dextrose',
  'palatinose',
  'hipercalorico',
  'hipercalórico',
  'mass gainer',
  'barra de proteina',
  'barra proteica',
  'protein bar',
  'albumina',
  'pasta de amendoim',
  'nitrato',
  'nitric oxide',
  'oxido nitrico',
  'óxido nítrico',
  'isolate',
  'isolado',
  'concentrado',
  'concentrate',
  'hidrolisado',
  'hydrolyzed',
  '3w',
  'top whey',
  'femini',
  'vegano',
  'vegan',
  'plant based',
  'plant-based',
];

const TERMOS_BLOQUEADOS = [
  'celular',
  'smartphone',
  'iphone',
  'samsung galaxy',
  'motorola',
  'capa',
  'pelicula',
  'película',
  'fone',
  'headphone',
  'earphone',
  'carregador',
  'cabo usb',
  'adaptador',
  'suporte veicular',
  'notebook',
  'laptop',
  'tablet',
  'smartwatch',
  'relogio',
  'relógio',
  'tv',
  'televisao',
  'televisão',
  'monitor',
  'mouse',
  'teclado',
  'impressora',
  'scanner',
  'roteador',
  'modem',
  'webcam',
  'caixa de som',
  'soundbar',
  'microfone',
  'liquidificador',
  'batedeira',
  'cafeteira',
  'aspirador',
  'ventilador',
  'climatizador',
  'umidificador',
  'camisa',
  'camiseta',
  'bermuda',
  'calça',
  'tenis',
  'tênis',
  'sapato',
  'bone',
  'boné',
  'mochila',
  'bolsa',
  'carteira',
  'cinto',
  'perfume',
  'colonia',
  'colônia',
  'maquiagem',
  'batom',
  'shampoo',
  'brinquedo',
  'boneco',
  'jogo',
  'video game',
  'livro',
  'ebook',
  'kindle',
  'revista',
  'pilha',
  'bateria',
  'lampada',
  'lâmpada',
];

export function isSuplemento(nome: string): boolean {
  const nomeLower = nome.toLowerCase();

  for (const bloqueado of TERMOS_BLOQUEADOS) {
    if (nomeLower.includes(bloqueado)) return false;
  }

  for (const termo of TERMOS_SUPLEMENTO) {
    if (nomeLower.includes(termo)) return true;
  }

  const nomeSemAcento = nomeLower.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

  for (const termo of TERMOS_SUPLEMENTO) {
    const termoSemAcento = termo.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    if (nomeSemAcento.includes(termoSemAcento)) return true;
  }

  return false;
}
